--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/vgui/ttt/icon_brain.vmt" )
	resource.AddFile( "materials/vgui/ttt/icon_brain.vtf" )
	resource.AddFile( "materials/vgui/ttt/perks/clairvoyant_perk_hud.png" )
end